# Generated by Django 4.0.4 on 2022-05-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doc_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploadedimages/')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
